port: "8000"


db:
  username: "postgres"
  host: "db"
  port: "5432"
#  host: "localhost"
#  port: "5436"
  dbname: "postgres"
  sslmode: "disable"
  timezone: "Europe/Moscow"
  # timezone: "America/Los_Angeles"
